### ISSUE TITLE
Linked Gist is gone, use this link instead

### ISSUE THREAD

**Issue by hindol** [jasjisdo/DirectoryWatchService#1]
Hi Jaschar,

Apologies for creating an issue. Could not think of another way to communicate. I previously owned the `hindol-viz` GitHub user, but unfortunately that account is gone (I fucked up). Do you mind updating the link to point to this repository instead?

https://github.com/Hindol/commons

Thanks,
Hindol

**Comment by jasjisdo** [comment]
Of course, I will update the link no problem.

**Comment by jasjisdo** [comment]
Done
